export type ModuleStatus = "Planned" | "Backlog" | "In Progress"

export type ModuleKind = "System" | "Feature" | "Area"

export type ModuleHealth = "On Track" | "Watch" | "Blocked"

export interface ModuleOwner {
  name: string
  initials: string
  role: string
  avatar?: string
}

export interface ModuleRecord {
  id: string
  name: string
  kind: ModuleKind
  owner: ModuleOwner
  domain: string
  progress: number
  tasksCompleted: number
  tasksTotal: number
  contributors: number
  blockers: number
  health: ModuleHealth
  dateStart: string
  dateEnd: string
  dateRange: string
  status: ModuleStatus
  favorite: boolean
}

export const MODULE_STATUS_OPTIONS: ModuleStatus[] = [
  "Planned",
  "Backlog",
  "In Progress",
]

const moduleOwners = {
  maya: {
    name: "Nora Vale",
    initials: "NV",
    role: "ReUI release lead",
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=96&h=96&dpr=2&q=80",
  },
  jonah: {
    name: "Jonah Lee",
    initials: "JL",
    role: "ReUI product ops",
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=96&h=96&dpr=2&q=80",
  },
  nina: {
    name: "Nina Santos",
    initials: "NS",
    role: "Docs owner",
    avatar:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=96&h=96&dpr=2&q=80",
  },
  elijah: {
    name: "Elijah Morgan",
    initials: "EM",
    role: "License lead",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=96&h=96&dpr=2&q=80",
  },
  priya: {
    name: "Priya Shah",
    initials: "PS",
    role: "Lifecycle PM",
    avatar:
      "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=96&h=96&dpr=2&q=80",
  },
  omar: {
    name: "Omar Haddad",
    initials: "OH",
    role: "Trust owner",
    avatar:
      "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=96&h=96&dpr=2&q=80",
  },
  sofia: {
    name: "Sofia Romero",
    initials: "SR",
    role: "Content lead",
    avatar:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=96&h=96&dpr=2&q=80",
  },
  kenji: {
    name: "Kenji Tan",
    initials: "KT",
    role: "Platform lead",
    avatar:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=96&h=96&dpr=2&q=80",
  },
  lena: {
    name: "Lena Wade",
    initials: "LW",
    role: "Developer tools",
  },
} satisfies Record<string, ModuleOwner>

export const MODULE_RECORDS: ModuleRecord[] = [
  {
    id: "core-workflow",
    name: "Registry Sync",
    kind: "System",
    owner: moduleOwners.maya,
    domain: "registry.reui.io",
    progress: 25,
    tasksCompleted: 8,
    tasksTotal: 32,
    contributors: 6,
    blockers: 0,
    health: "On Track",
    dateStart: "2026-04-17",
    dateEnd: "2026-05-01",
    dateRange: "Apr 17 - May 01, 2026",
    status: "Planned",
    favorite: false,
  },
  {
    id: "onboarding-flow",
    name: "Pro Onboarding",
    kind: "Feature",
    owner: moduleOwners.jonah,
    domain: "pro.reui.io",
    progress: 0,
    tasksCompleted: 0,
    tasksTotal: 18,
    contributors: 4,
    blockers: 0,
    health: "Watch",
    dateStart: "2026-04-19",
    dateEnd: "2026-05-03",
    dateRange: "Apr 19 - May 03, 2026",
    status: "Backlog",
    favorite: false,
  },
  {
    id: "workspace-setup",
    name: "Docs Portal",
    kind: "Area",
    owner: moduleOwners.nina,
    domain: "docs.reui.io",
    progress: 0,
    tasksCompleted: 2,
    tasksTotal: 14,
    contributors: 3,
    blockers: 1,
    health: "Blocked",
    dateStart: "2026-04-21",
    dateEnd: "2026-05-05",
    dateRange: "Apr 21 - May 05, 2026",
    status: "In Progress",
    favorite: false,
  },
  {
    id: "permission-matrix",
    name: "Access Matrix",
    kind: "System",
    owner: moduleOwners.maya,
    domain: "admin.reui.io",
    progress: 42,
    tasksCompleted: 11,
    tasksTotal: 26,
    contributors: 5,
    blockers: 0,
    health: "Watch",
    dateStart: "2026-04-22",
    dateEnd: "2026-05-06",
    dateRange: "Apr 22 - May 06, 2026",
    status: "In Progress",
    favorite: true,
  },
  {
    id: "billing-rules",
    name: "License Billing",
    kind: "Feature",
    owner: moduleOwners.elijah,
    domain: "billing.reui.io",
    progress: 64,
    tasksCompleted: 21,
    tasksTotal: 33,
    contributors: 7,
    blockers: 0,
    health: "On Track",
    dateStart: "2026-04-18",
    dateEnd: "2026-05-02",
    dateRange: "Apr 18 - May 02, 2026",
    status: "In Progress",
    favorite: false,
  },
  {
    id: "notification-center",
    name: "Release Notes",
    kind: "Area",
    owner: moduleOwners.priya,
    domain: "changelog.reui.io",
    progress: 18,
    tasksCompleted: 5,
    tasksTotal: 28,
    contributors: 4,
    blockers: 2,
    health: "Blocked",
    dateStart: "2026-04-23",
    dateEnd: "2026-05-09",
    dateRange: "Apr 23 - May 09, 2026",
    status: "Backlog",
    favorite: false,
  },
  {
    id: "audit-trail",
    name: "Trust Audit",
    kind: "System",
    owner: moduleOwners.omar,
    domain: "trust.reui.io",
    progress: 76,
    tasksCompleted: 19,
    tasksTotal: 25,
    contributors: 5,
    blockers: 0,
    health: "On Track",
    dateStart: "2026-04-15",
    dateEnd: "2026-04-30",
    dateRange: "Apr 15 - Apr 30, 2026",
    status: "In Progress",
    favorite: true,
  },
  {
    id: "template-library",
    name: "Block Library",
    kind: "Feature",
    owner: moduleOwners.sofia,
    domain: "blocks.reui.io",
    progress: 33,
    tasksCompleted: 10,
    tasksTotal: 30,
    contributors: 6,
    blockers: 0,
    health: "Watch",
    dateStart: "2026-04-24",
    dateEnd: "2026-05-10",
    dateRange: "Apr 24 - May 10, 2026",
    status: "Planned",
    favorite: false,
  },
  {
    id: "integration-hub",
    name: "Integration Hub",
    kind: "Area",
    owner: moduleOwners.kenji,
    domain: "integrations.reui.io",
    progress: 58,
    tasksCompleted: 14,
    tasksTotal: 24,
    contributors: 8,
    blockers: 1,
    health: "Watch",
    dateStart: "2026-04-20",
    dateEnd: "2026-05-04",
    dateRange: "Apr 20 - May 04, 2026",
    status: "In Progress",
    favorite: false,
  },
  {
    id: "api-console",
    name: "API Console",
    kind: "Feature",
    owner: moduleOwners.lena,
    domain: "api.reui.io",
    progress: 91,
    tasksCompleted: 29,
    tasksTotal: 32,
    contributors: 4,
    blockers: 0,
    health: "On Track",
    dateStart: "2026-04-12",
    dateEnd: "2026-04-26",
    dateRange: "Apr 12 - Apr 26, 2026",
    status: "In Progress",
    favorite: true,
  },
  {
    id: "role-automation",
    name: "Role Automation",
    kind: "System",
    owner: moduleOwners.maya,
    domain: "admin.reui.io",
    progress: 12,
    tasksCompleted: 3,
    tasksTotal: 25,
    contributors: 3,
    blockers: 1,
    health: "Blocked",
    dateStart: "2026-04-25",
    dateEnd: "2026-05-12",
    dateRange: "Apr 25 - May 12, 2026",
    status: "Backlog",
    favorite: false,
  },
  {
    id: "workspace-invites",
    name: "Team Invites",
    kind: "Feature",
    owner: moduleOwners.jonah,
    domain: "teams.reui.io",
    progress: 47,
    tasksCompleted: 15,
    tasksTotal: 32,
    contributors: 5,
    blockers: 0,
    health: "Watch",
    dateStart: "2026-04-19",
    dateEnd: "2026-05-06",
    dateRange: "Apr 19 - May 06, 2026",
    status: "Planned",
    favorite: false,
  },
  {
    id: "release-checklist",
    name: "Release Checklist",
    kind: "Area",
    owner: moduleOwners.nina,
    domain: "release.reui.io",
    progress: 84,
    tasksCompleted: 26,
    tasksTotal: 31,
    contributors: 7,
    blockers: 0,
    health: "On Track",
    dateStart: "2026-04-16",
    dateEnd: "2026-05-01",
    dateRange: "Apr 16 - May 01, 2026",
    status: "In Progress",
    favorite: false,
  },
  {
    id: "reporting-digest",
    name: "Usage Digest",
    kind: "Feature",
    owner: moduleOwners.priya,
    domain: "reports.reui.io",
    progress: 5,
    tasksCompleted: 2,
    tasksTotal: 38,
    contributors: 3,
    blockers: 0,
    health: "Watch",
    dateStart: "2026-04-28",
    dateEnd: "2026-05-16",
    dateRange: "Apr 28 - May 16, 2026",
    status: "Backlog",
    favorite: false,
  },
  {
    id: "security-review",
    name: "Security Review",
    kind: "System",
    owner: moduleOwners.omar,
    domain: "trust.reui.io",
    progress: 69,
    tasksCompleted: 18,
    tasksTotal: 26,
    contributors: 6,
    blockers: 2,
    health: "Blocked",
    dateStart: "2026-04-18",
    dateEnd: "2026-05-07",
    dateRange: "Apr 18 - May 07, 2026",
    status: "In Progress",
    favorite: false,
  },
  {
    id: "help-center",
    name: "Help Center",
    kind: "Area",
    owner: moduleOwners.sofia,
    domain: "help.reui.io",
    progress: 39,
    tasksCompleted: 9,
    tasksTotal: 23,
    contributors: 4,
    blockers: 0,
    health: "On Track",
    dateStart: "2026-04-23",
    dateEnd: "2026-05-11",
    dateRange: "Apr 23 - May 11, 2026",
    status: "Planned",
    favorite: false,
  },
  {
    id: "data-retention",
    name: "Data Retention",
    kind: "System",
    owner: moduleOwners.kenji,
    domain: "privacy.reui.io",
    progress: 22,
    tasksCompleted: 7,
    tasksTotal: 32,
    contributors: 5,
    blockers: 1,
    health: "Watch",
    dateStart: "2026-04-27",
    dateEnd: "2026-05-14",
    dateRange: "Apr 27 - May 14, 2026",
    status: "Backlog",
    favorite: false,
  },
]

export const revenueData = [
  { value: 1000 },
  { value: 4500 },
  { value: 2000 },
  { value: 5200 },
  { value: 1500 },
  { value: 6100 },
  { value: 3000 },
  { value: 6800 },
  { value: 2000 },
  { value: 1000 },
  { value: 4000 },
  { value: 2000 },
  { value: 3000 },
  { value: 2000 },
  { value: 6238 },
]

export const customersData = [
  { value: 2000 },
  { value: 4500 },
  { value: 2000 },
  { value: 5200 },
  { value: 1500 },
  { value: 5100 },
  { value: 2500 },
  { value: 6800 },
  { value: 1800 },
  { value: 1000 },
  { value: 3000 },
  { value: 2000 },
  { value: 2700 },
  { value: 2000 },
  { value: 4238 },
]

export const activeUsersData = [
  { value: 2000 },
  { value: 3500 },
  { value: 2000 },
  { value: 5200 },
  { value: 1200 },
  { value: 4100 },
  { value: 3500 },
  { value: 5800 },
  { value: 2000 },
  { value: 800 },
  { value: 3000 },
  { value: 1000 },
  { value: 4000 },
  { value: 2000 },
  { value: 4238 },
]

export type TeamMember = {
  src: string
  name: string
  initials: string
}

export const TEAM_MEMBERS: TeamMember[] = [
  {
    src: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=96&h=96&dpr=2&q=80",
    name: "Mira Stone",
    initials: "MS",
  },
  {
    src: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=96&h=96&dpr=2&q=80",
    name: "Alex Johnson",
    initials: "AJ",
  },
  {
    src: "https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=96&h=96&dpr=2&q=80",
    name: "Sarah Chen",
    initials: "SC",
  },
]

export const TEAM_EXTRA_COUNT = 8