/**
 * The app's icon vocabulary, in one place.
 *
 * Phase 5 of the ReUI/Maia migration. The app was running TWO icon libraries at
 * once, split by layer: every vendored ReUI/shadcn primitive and block drew
 * Hugeicons (base-maia's set), while all of our own code drew lucide. Both
 * families rendered side by side on every screen with different stroke weights
 * and optical sizes, which is what "the icons are just wrong" looked like.
 *
 * The direction was forced: the ~70 Hugeicons files are vendored and get
 * regenerated by the shadcn CLI, so they cannot be hand-edited. Our 34 lucide
 * files can.
 *
 * Everything is re-exported under a lucide-flavoured alias so call sites read
 * the same as before, and — more importantly — so revising a glyph is ONE edit
 * here rather than a hunt through call sites. Glyph choice is a design
 * decision and will get revised; the indirection is the point.
 *
 * Usage keeps the ReUI idiom, so our icons and the primitives' icons are
 * literally the same component:
 *
 *   import { HugeiconsIcon } from '@hugeicons/react';
 *   import { HomeIcon } from '@/components/ui/icons';
 *
 *   <HugeiconsIcon icon={HomeIcon} size={17} strokeWidth={1.6} />
 */
export {
  // ── Navigation ────────────────────────────────────────────────────────────
  Home01Icon as HomeIcon,
  /** "Propositions" nav + proposal rows. An invoice reads closer to a
   *  commercial proposal than lucide's literal ScrollText did. */
  Invoice01Icon as ProposalIcon,
  HelpCircleIcon as HelpIcon,
  UserMultipleIcon as UsersIcon,
  SlidersHorizontalIcon as SlidersIcon,
  HistoryIcon as HistoryIcon,
  ChevronLeftIcon as ChevronLeftIcon,
  ChevronRightIcon as ChevronRightIcon,
  ArrowRight01Icon as ArrowRightIcon,

  // ── Actions ───────────────────────────────────────────────────────────────
  PlusSignIcon as PlusIcon,
  Cancel01Icon as XIcon,
  Delete02Icon as TrashIcon,
  Copy01Icon as CopyIcon,
  Download01Icon as DownloadIcon,
  FloppyDiskIcon as SaveIcon,
  PencilEdit01Icon as PencilIcon,
  RefreshIcon as RefreshIcon,
  ArrowTurnBackwardIcon as RotateCcwIcon,
  Undo02Icon as UndoIcon,
  Archive02Icon as ArchiveIcon,
  MailSend01Icon as SendIcon,
  Logout01Icon as LogOutIcon,
  UserAdd01Icon as UserPlusIcon,
  Search01Icon as SearchIcon,
  Settings01Icon as SettingsIcon,
  ExternalLinkIcon as ExternalLinkIcon,
  MoreHorizontalIcon as MoreHorizontalIcon,
  MoreVerticalIcon as MoreVerticalIcon,

  // ── State / feedback ──────────────────────────────────────────────────────
  Alert02Icon as AlertTriangleIcon,
  CheckmarkCircle02Icon as CheckCircleIcon,
  CheckIcon as CheckIcon,
  InformationCircleIcon as InfoIcon,
  BanIcon as BanIcon,
  /** Matches the Spinner primitive, which already uses Loading03Icon. */
  Loading03Icon as LoaderIcon,

  // ── Content ───────────────────────────────────────────────────────────────
  File01Icon as FileTextIcon,
  BookOpen01Icon as BookOpenIcon,
  BarChartIcon as BarChartIcon,
  HashIcon as HashIcon,
  Mail01Icon as MailIcon,
  EyeIcon as EyeIcon,
  EyeOffIcon as EyeOffIcon,

  // ── Theme switcher ────────────────────────────────────────────────────────
  Sun02Icon as SunIcon,
  Moon02Icon as MoonIcon,
  ComputerIcon as MonitorIcon,
} from '@hugeicons/core-free-icons';
